### ISSUE TITLE
Could not initialize Margo inside an initialized mpi-process

### ISSUE THREAD

**Issue by ctminh** [mochi-hpc/mochi-thallium#1]
Hi, I'm quite interested in thallium. On my side, if I include mpi.h, and init MPI processes, then use one of the ranks for creating thallium-engine server-mode, it throws an exception like that:
_terminate called after throwing an instance of 'thallium::margo_exception'
engine.hpp:122][margo_init] Could not initialize Margo_
Otherwise, if I don't init mpi, it's fine. So, do you have any suggestions for this? If I want to deploy a mpi program: multiple ranks and each rank has multiple threads inside, one thread could perform thallium-rpc services.
Thanks!

**Comment by mdorier** [comment]
Which platform are you using, and which transport method? Sometimes MPI and libfabric (used by Mercury) will conflict for access to the network. On Cray systems with s GNI network (e.g. NERSC Cori or ANL Theta) for example you need to set this environment variable:
```
export MPICH_GNI_NDREG_ENTRIES=1024
```
Something similar might be needed in your case.

**Comment by ctminh** [comment]
Thanks for your quick reply! I'm using this cluster (https://doku.lrz.de/display/PUBLIC/Linux+Cluster), CooLMUC-2 Cluster with 28-way Haswell-based nodes and FDR14 Infiniband interconnect, used for both serial and parallel processing. Is it Ok? Regarding MPI stuff, it's intel mpi.

**Comment by mdorier** [comment]
@ctminh what protocol are you passing to the thallium engine? `ofi+verbs`?
@soumagne and @carns do you know of any conflict between libfabric and intel-mpi or infiniband-based MPI?

**Comment by ctminh** [comment]
**what protocol are you passing to the thallium engine? ofi+verbs?**
Ahha, to be honest, I don't really have much experience with this. So, anyway, playing around with thallium examples, I create th-engine server as default: _tl::engine ser_engine("tcp", THALLIUM_SERVER_MODE);_
Then, at the client-side, copy and paste the server-addr, it would be: _ofi+tcp;ofi_rxm://10.7.4.178:33355_, for example.

**Comment by mdorier** [comment]
Ah I see, so you are using TCP. You might want to try verbs (who knows, maybe MPI is messing up with TCP, and at least you would get better performance out of your network), by compiling libfabric with the following variants: `fabrics=tcp,verbs,rxm,mrail`. I haven't used verbs myself but I know that using it is not as simple as changing "tcp" into "verbs" when initializing the engine. @soumagne and @carns might be able to help you here.

**Comment by mdorier** [comment]
If you install via spack, you can just install thallium as follows:

```
spack install mochi-thallium ^libfabric fabrics=tcp,verbs,rxm,mrail
```

Alternatively you can put this in your `~/.spack/packages.yaml` file:

```
spack:
  packages:
    libfabric:
      variants: fabrics=verbs,rxm,mrail
      buildable: true
      version: []
      target: []
      providers: {}
      compiler: []
```

**Comment by ctminh** [comment]
Ah great! Good to know that! :) I'll try then.

**Comment by carns** [comment]
One other tip to add for configuring verbs.  When you add "verbs" to the fabric variant for libfabric, it will introduce dependency on another library called `rdma-core`.  Spack will compile it's own copy by default.

There isn't anything technically wrong with the version of rdma-core that Spack will build, but for compatibility and support you will be better off using the existing library on your system, provided by the IB vendor.  This will be a system package called either rdma-core or mofed (either one provides essentially the same thing for our purposes, just named differently).

You can tell spack to use the system-provided rdma-core (regardless of what it's called) by putting lines like this in either your packages.yaml or your spack.yaml (the latter if you are using a Spack environment):

https://github.com/mochi-hpc-experiments/mochi-tests/blob/main/perf-regression/summit/packages.yaml#L41
https://github.com/mochi-hpc-experiments/platform-configurations/blob/master/ORNL/Summit/spack.yaml#L102

Beyond that trick there shouldn't be much else to do (famous last words).  Just use "verbs" in place of "tcp" when initializing thallium.

**Comment by ctminh** [comment]
Hi @mdorier and @carns, thank you both! I got it running. Using "verbs" in place of "tcp" was already fine. I also used the system-provided rdma-core as you suggested.

**Comment by mdorier** [comment]
Great!
