### ISSUE TITLE
Regression in thallium::engine constructor with pools

### ISSUE THREAD

**Issue by jspanchu** [mochi-hpc/mochi-thallium#11]
Constructing an engine with `engine::engine(const std::string& addr, int mode, const pool& progress_pool, const pool& default_handler_pool)` overload no longer works. This error shows up.

Code:
```cpp
auto rpc_pool = tl::pool::create(tl::pool::access::mpsc, tl::pool::kind::fifo_wait);
auto rpc_xstream = tl::xstream::create(tl::scheduler::predef::basic_wait, *rpc_pool);
auto progress_pool = tl::pool::create(tl::pool::access::mpsc, tl::pool::kind::fifo_wait);
auto progress_xstream = tl::xstream::create(tl::scheduler::predef::basic_wait, *progress_pool);

tl::engine myEngine("tcp", THALLIUM_SERVER_MODE, *progress_pool, *rpc_pool);
```

Error:
```sh
[trace] Validating JSON configuration
[trace] Initializing Mercury
[error] Could not initialize hg_class with protocol (null)
terminate called after throwing an instance of 'thallium::margo_exception'
  what():  [/home/local/KHQ/jaswant.panchumarti/Documents/code/async/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-10.3.0/mochi-thallium-develop-5ii53qdxn7chgbogcu7ifhijtxsox3tm/include/thallium/engine.hpp:947][margo_init_ext] Could not initialize Margo
Aborted (core dumped)
```

Bisected the regression to this commit.
https://github.com/mochi-hpc/mochi-thallium/commit/a34bc324f17021102b72cf30d7703b5aae213f1d#diff-c77ab3f9df8ac239f4ac58104ba84c986b7d19806faa04e1569a5b7b635c6e64L942

**Comment by mdorier** [comment]
Thanks for reporting this issue. Can you try with the current main branch? I just pushed a commit that should fix it. (you can install `mochi-thallium@main` if you're using spack). Once you confirm that it works, I will make a patch release.

**Comment by jspanchu** [comment]
That commit fixed the bug. Thanks!

**Comment by mdorier** [comment]
Thanks, I created release 0.11.1 and added it to mochi-spack-packages.
