### ISSUE TITLE
Feature request: Support passing local objects to RPC handlers

### ISSUE THREAD

**Issue by alberto-miranda** [mochi-hpc/mochi-thallium#13]
While defining RPC handlers for a service of ours, we are currently in need of accessing context information from outside of the RPC handler scope. The code below exemplifies this:

```c++
#include <thallium.hpp>
#include <iostream>

// handlers.hpp
struct context_info {
    std::string m_foo;
    std::string m_bar;
};

namespace tl = thallium;

void hello_rpc(const tl::request& req) {
    //  the `context_info` defined in `main` is needed here
    std::cout << "Hello World!" << std::endl;
}

// main.cpp
#include "handlers.hpp"

int main(int argc, char** argv) {

    context_info extra_info{"foo", "bar"};

    tl::engine myEngine("tcp", THALLIUM_SERVER_MODE);
    myEngine.define("hello", hello_rpc).disable_response();
    std::cout << "Server running at address " << myEngine.self() << std::endl;

    return 0;
}
```

This kind of situation can typically be solved by:
1. using globals (bleh)
2. using a singleton (better than globals, but still lacking)
3. using a lambda and capturing the `context_info` (this would work if the handlers were defined in the same file, but we have dozens of handlers in separate files). 
 
Ideally, it would be really nice if we could just inject extra arguments into the RPC handler definition so that Thallium could just propagate them to the handler when the RPC is received similarly to what is done with the `tl::request` information argument.

Thus, our problem above would end up as follows:

```c++
// handlers.hpp
#include <thallium.hpp>
#include <iostream>

struct context_info {
    std::string m_foo;
    std::string m_bar;
};

namespace tl = thallium;

void hello_rpc(const tl::request& req, const context_info& info) {
    std::cout << "Hello World!" << std::endl;
    // do something interesting with `info.foo`
}

// main.cpp
#include "handlers.hpp"

int main(int argc, char** argv) {

    context_info extra_info{"foo", "bar", "baz"};

    tl::engine myEngine("tcp", THALLIUM_SERVER_MODE);
    myEngine.define("hello", hello_rpc, extra_info).disable_response();
    std::cout << "Server running at address " << myEngine.self() << std::endl;

    return 0;
}
```

From Thallium's code itself, this looks like it should be possible to add without much fuss, but of course I may be missing something.

**Comment by alberto-miranda** [comment]
Interesting. I still think that having the ability to piggyback information into RPC handlers could be a useful addition to Thallium, but we can probably make it work with a bit of code massaging. I'll play a bit with it and let you know.

**Comment by mdorier** [comment]
You would envision something like the following?

```
void my_rpc(const tl::request& req, const my_context& ctx, int x, int y) {
   ...
}

my_context ctx{};

engine.define("my_rpc", my_rpc, tl::rpc_context(std::ref(ctx)), ...)
```

My concern is that any context you would want to pass to the RPC like this would look like an RPC argument rather than a local context. Besides, thallium would end up doing exactly what you could have done manually, namely wrapping the actual function call into a lambda with the proper capture, but with a lot of template deduction machinery to handle all the possible cases (return value present or not, tl::request present or not, etc.).

Or do you have something else in mind?

**Comment by mdorier** [comment]
I feel like between what I've described above and writing the following, there is not much difference:

```
std::function<void(const tl::request&, int, int)> rpc = [&ctx](const tl::request& req, int x, int y){
    my_rpc(req, ctx, x, y);
};
engine.define("my_rpc", rpc);
```
and the lambda version looks clearer to me...

**Comment by mdorier** [comment]
Adding the context to the `tl::request` could be an idea, but we would loose type information (we would have to cast the context to a `void*` internally then have a `get_context<T>()` member function that cast it back, trusting that the user knows what they are casting into).

What you could use though is use `std::bind`, passing the context as first parameter:

```
void ping(const context& ctx, const tl::request& req) { ... }

context ctx{};
engine.define("ping", std::bind(ping, std::cref(ctx)));
```

(not tested)

**Comment by alberto-miranda** [comment]
Using a `provider` class was in fact the better solution for our current problem. We had to restructure the code a fair bit, but once done it is working without issues. Having the handlers properly encapsulated in a custom `server` class was also beneficial since it helped us get rid of some global state that was required by the handlers: this state has now become proper members of the custom `server` class. Thanks!
