### ISSUE TITLE
Best practice for asynchronous calls

### ISSUE THREAD

**Issue by dyokelson** [mochi-hpc/mochi-thallium#19]
Hello @mdorier I am unable to assign you but following up from slack here. I have a thallium client function that only _sometimes_ submits an asynchronous rpc. I would like to have a default response for it to return when it does not. Is there a way to initialize an empty/default thallium::async_response? It looks like the constructor is private. Or I guess what would be the best way to handle this? I was also looking at the code example for computeSum within the thallium template - how I can pass in an AsyncRequest pointer as an argument, is this the best way to handle all asynchronous calls? In other asynchronous calls I am just creating the async_response and returning it, so this AsyncRequest implementation would be a different return type, and ideally they would be consistent. Does my question make sense? Here is the part of the example computeSum code I mentioned:
```
} else { // asynchronous call
    auto async_response = rpc.on(ph).async(collector_id, x, y);
    auto async_request_impl =
      std::make_shared<AsyncRequestImpl>(std::move(async_response));
    async_request_impl->m_wait_callback =
      [result](AsyncRequestImpl& async_request_impl) {
        RequestResult<int32_t> response =
          async_request_impl.m_async_response.wait();
          if(response.success()) {
            if(result) *result = response.value();
          } else {
            throw Exception(response.error());
          }
      };
    *req = AsyncRequest(std::move(async_request_impl));
  } 
```

**Comment by mdorier** [comment]
I am not super in favor of providing a default constructor for `async_response` because it would mean other functions would have to track the validity of the `async_response` object.

The thallium microservice template shows an example for letting the caller choose whether to use a blocking or non-blocking call, but you can imagine other mechanisms. `async_response` still has a move-constructor and a move-assignment operator so you can do a lot with them. If you use C++17 (or Boost), you could store it in an `std::optional` or `boost::optional`, for instance.

You say "I have a thallium client function that only sometimes submits an asynchronous rpc". What does it look like from the perspective of the caller? How do they know whether they have to wait on something?

**Comment by dyokelson** [comment]
Sure, that makes sense about the default constructor, I think in my case I would want to check the validity of it, but I see why you wouldn't want that as general behavior. 

How things are implemented it so far is that we have a list of async_response objects from any asynchronous requests - these are checked before the system shuts down to make sure they are all complete, we don't wait on them until the very end of the program. For the sometimes submit an rpc call: the program calls "commit" for example on the client and we decrement a counter (configurable), when the counter reaches 0 we actually submit the rpc, otherwise we do nothing and no response is generated (this is where I was hoping we'd have something default I could essentially set to "complete" to return). This allows basic logic to be implemented in the program and puts the ownership on our thallium client to track that configuration. 

I think I will have to do some redesign of our current implementation - I really like the idea of using std::optional, but we are currently on C++14, I am suspicious we'll hit other errors in our integrations with a version upgrade but I may try that. I'll think on some other things, hopefully our use case makes more sense now?

**Comment by mdorier** [comment]
With C++14 you probably have `std::experimental::optional`. But I'm not sure I understand your explanation. Can you show me a sample code of what this would look like if async_response had a default constructor, and what it looks like calling your functions from the user's point of view?

**Comment by dyokelson** [comment]
Sure, here is the current implementation from the user's point of view - before implementing the "sometimes" async call.
```
static std::vector<thallium::async_response> requests;
auto response = client_handle.publish_async(node);
requests.push_back(std::move(response));
// at program shutdown check for any unfinished requests
for(auto i = requests.begin(); i != requests.end(); i++) {
        i->wait();
    }
```
The trouble with this implementation is when implementing a call on the client handle that only sometimes returns a response. For example:
```
static std::vector<thallium::async_response> requests;
auto response = client_handle.publish_async(node);
// if the response is valid add it to the list
if valid(response) {
        requests.push_back(std::move(response));
}
// at program shutdown check for any unfinished requests
for(auto i = requests.begin(); i != requests.end(); i++) {
        i->wait();
    }
```

This has given me an idea though - I think I can move the list of requests into the client handle class and then just be able to call "client_handle.finalize_requests()" or something to make sure we have waited on them all to complete before shutting down. This should work in this context since we don't actually need the response, just want to make sure they've completed, and this is possibly better to remove the ownership from the user and give it to the client handle. We would never need return anything from the client handle asynchronous functions. Do you see any issues with this approach? The other would be to switch to the the optional return value.

**Comment by mdorier** [comment]
I think what you would need is the possibility to call `wait` on an `async_response` multiple times. That way your code would look like this:

```
tl::async_response sometimes_publish_async(node) {
     auto response = rpc.on(node).async(x,y,z);
     if( /* condition for blocking */) {
        response.wait();
     }
     return response;
}
```

That way your `sometimes_publish_async` function will always return a valid `async_response`, i.e. something you can wait on and from which you can get the response data.

I can implement that.

The idea with either `std::unique_ptr` or `std::optional` would have been as follows:

```
/* with unique_ptr */
std::unique_ptr<tl::async_response> sometimes_publish_async(node) {
     auto response = rpc.on(node).async(x,y,z);
     if( /* condition for blocking */) {
        response.wait();
        return nullptr;
     }
     return std::make_unique<tl::async_response>(std::move(response));
}

/* with optional */
std::optional<tl::async_response> sometimes_publish_async(node) {
     auto response = rpc.on(node).async(x,y,z);
     if( /* condition for blocking */) {
        response.wait();
        return std::nullopt;
     }
     return response;
}

/* in both cases, at program shutdown: */
for(auto& response : requests) {
    if(response) {
        response->wait();
    }
}
```

**Comment by mdorier** [comment]
Ok, it's added in the main branch, you can now wait multiple times on the request. Let me know if this works for you.

Note: keeping a large number of requests around and only waiting on them at the end isn't great, for two reasons:
- Margo/Thallium have a mechanism that caches RPC handles and reuse them. Until you no longer have any reference to a handle, Margo/Thallium won't be able to reuse it, so they will have to create new ones each time you issue a new RPC.
- Mercury keeps data associated with RPC arguments and responses in a large contiguous, cyclic buffer. Say you have issued 3 RPCs and received responses for them, the buffer will contain `[response for RPC 1][response for RPC 2][response for RPC 3][ free space ... ]`. Again, until you are done with the handle associated with RPC 1, Mercury won't be able to reclaim the part of the buffer that contains its serialized data. It will have to keep appending to the buffer, until it runs out of space and have to allocate another buffer.

What you can do to prevent that is from time to time have a procedure that looks into the `requests` vector, `test` the requests, `wait` on them if `test` returns true, and removes them from the `requests` vector.

**Comment by dyokelson** [comment]
Thanks! I just implemented the std::experimental::optional route and will try that out. I will look into the changes you made as well. I am not sure if I fully understand them yet - need to dig into the changes. 

I will update here when I have been able to run/test out the new calls.

**Comment by dyokelson** [comment]
Hi @mdorier back with an update - the optional return type worked for my needs! I will actually also likely use the ability to wait on a response twice too, since I will be intermittently doing things with the requests in certain scenarios. However, I have not needed to implement it yet. But at the moment all is working, thanks so much for your help!

**Comment by mdorier** [comment]
Great! Note that I released a new version of thallium a couple days ago so if you need the ability to wait multiple times on a request, it's now in a release.
