### ISSUE TITLE
Add cereal dependency in thallium.pc and in thallium-config.cmake.in

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc/mochi-thallium#2]
Those dependencies are needed, otherwise codes using thallium need to find cereal by themselves.

**Comment by hyoklee** [comment]
Is it possible to disable 
```
find_dependency (cereal)
```
in thallium-config.cmake.in when ENABLE_CEREAL is OFF?

**Comment by mdorier** [comment]
@hyoklee  Can you check if my last commit resolves this?

**Comment by hyoklee** [comment]
@mdorier , yes, it resolved the issue. Thank you for fixing it so quickly!
