### ISSUE TITLE
Pass bulk attributes to Margo

### ISSUE THREAD

**Issue by thomas-bouvier** [mochi-hpc/mochi-thallium#6]
It doesn't seem possible to pass bulk attributes to the Margo instance. My current use case implies performing RDMA on CUDA memory:

```cpp
struct hg_bulk_attr attr; // Margo attributes
attr.mem_type = HG_MEM_TYPE_CUDA
hg_return_t ret = margo_bulk_create_attr(..., &attr, ...);
```

With the current Thallium API, bulks are created using the engine's `expose()` method. The ability to pass Margo attributes to this method (such as the one above) would be nice to have.

The implementation of `expose()` should probably be similar to the following:

```cpp
inline bulk engine::expose(const std::vector<std::pair<void*, size_t>>& segments, bulk_mode flag, const hg_bulk_attr& attr) {
    g_bulk_t handle;
    hg_uint32_t count = c;
    tl::bulk_mode flag = tl::bulk_mode::read_only;
    std::vector<void*> buf_ptrs(count);
    std::vector<hg_size_t> buf_sizes(count);

    for (unsigned i = 0; i < segments.size(); i++) {
        buf_ptrs[i] = segments[i].first;
        buf_sizes[i] = segments[i].second;
    }

    hg_return_t ret = margo_bulk_create_attr(
            m_impl->m_mid, count, &buf_ptrs[0], &buf_sizes[0],
            static_cast<hg_uint32_t>(flag), &attr, &handle);
    return bulk(m_impl, handle, true);
}
```

@mdorier

**Comment by mdorier** [comment]
Thanks, I added the new function, can you try it by installing mochi-thallium@main and confirm that it works?
(Note that an alternative would have been to use `engine::wrap`, which is the function to use to wrap an existing `hg_bulk_t` in a `tl::bulk` instance).

**Comment by thomas-bouvier** [comment]
Registering some cuda memory as follows:

```cpp
struct hg_bulk_attr attr;
bool cuda = var.is_cuda();
if (cuda) {
    attr.mem_type = HG_MEM_TYPE_CUDA;
    attr.device = 0;
}

tl::bulk local_bulk = myEngine.expose(segments, tl::bulk_mode::write_only, attr);
```

I get the following error:

```
Function returned HG_OPNOTSUPPORTED
terminate called after throwing an instance of 'thallium::margo_exception'
  what():  [/opt/software/linux-ubuntu20.04-skylake_avx512/gcc-9.4.0/mochi-thallium-main-2cm2hywvbsk2thzr7thup7acpkxd7a6a/include/thallium/engine.hpp:1132][margo_bulk_create] Function returned HG_OPNOTSUPPORTED
Aborted (core dumped)
```

The following assert is causing it:
https://github.com/mochi-hpc/mochi-thallium/blob/5daa9a909d1309620ed874832cf8075644727a8a/include/thallium/engine.hpp#L1132

**Comment by carns** [comment]
The `HG_OPNOTSUPPORTED` probably indicates that either Mercury isn't initialized with device memory support, or else libfabric hasn't been built with CUDA support.  Sorry this isn't better documented yet, but:

To initialize Mercury with device memory you can specify it in the margo json parameters with something like this:
```
{
   "mercury": {
       "na_request_mem_device":true
   }
}
```
or alternatively, specify it in the init info struct explicitly as is done in https://github.com/mochi-hpc-experiments/mochi-tests/blob/main/perf-regression/gpu-margo-p2p-bw.cu#L190.

To build libfabric with CUDA support, you can use the libfabric spack package in our moch-spack-packages repo, which adds a `+cuda` variant to libfabric.  Or if you are building libfabric manually you can use the `--with-cuda` configure argument.

**Comment by mdorier** [comment]
Quick warning about your code: you need to initialize your `attr` variable in the non-cuda path too. C++ doesn't initializes to 0 for you.

**Comment by thomas-bouvier** [comment]
Closing this as atrtibutes are passed to Margo. Thanks :)
